# Generated by Django 4.1.7 on 2023-03-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('career', models.CharField(max_length=255)),
                ('liric_gender', models.CharField(max_length=30)),
                ('registration_day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
