# Generated by Django 3.2.18 on 2023-03-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_delete_item_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
