# Generated by Django 3.2.18 on 2023-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_day',
            field=models.DateField(),
        ),
    ]
